language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
install:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer install --ignore-platform-reqs
script:
    vendor/bin/phpunit
notifications:
  email: change
