language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  
install:
  - composer self-update
  - composer install --ignore-platform-reqs
  
  script:
    if [[ "$COVERAGE" == "1" ]]; then
      vendor/bin/phpunit --coverage-text
    else
      vendor/bin/phpunit
