language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
install:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer install --dev
script:
    vendor/bin/phpunit
notifications:
  email: change
